


SELECT * FROM EMPLOYEES
INSERT INTO EMPLOYEES VALUES(8,'RITESH','MALE',25000,'ANALYTICS',35)
INSERT INTO EMPLOYEES VALUES(9,'DATTESH','MALE',45000,'CLOUD',26)
INSERT INTO EMPLOYEES VALUES(10,'SUNIL','MALE',40000,'ANALYTICS',35)

INSERT INTO DEPARTMENT VALUES(1237,'ANALYTICS','CALIFORNIA')
INSERT INTO DEPARTMENT VALUES(1238,'CLOUD','NEW YORK')




--DELETE DUPLICATE ROWS 

DELETE FROM EMPLOYEES
WHERE EMPLOYEE_ID IN(
                     SELECT MAX(EMPLOYEE_ID)
                     FROM EMPLOYEES
                     GROUP BY EMPLOYEE_NAME,DEPT
                     HAVING COUNT(*)>1)
	SELECT * FROM EMPLOYEES




--DELETING DUPLICATE VALUES USING CTE(COMMON TABLE EXPRESSION)

;WITH CTE AS 
(
SELECT *, ROW_NUMBER() OVER(PARTITION BY EMPLOYEE_NAME ORDER BY EMPLOYEE_NAME) AS ROW_NUMBER
FROM EMPLOYEES
)
DELETE FROM CTE WHERE ROW_NUMBER>1

SELECT * FROM EMPLOYEES
--CREATING TEMP TABLE WOULD BE USEFUL FOR THIS QUERY SO YOU WILL NOT LOOSE YOUR ORIGINAL DATA 
--I RECOMMAND TO USE TEMP TABLE



--BY USING DERIVED TABLE

SELECT * FROM EMPLOYEES

DELETE EMPLOYEES FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_NAME ORDER BY EMPLOYEE_NAME DESC)
AS ROWNUMBER FROM EMPLOYEES)EMPLOYEES WHERE ROWNUMBER>1

SELECT * FROM EMPLOYEES
--CREATING TEMP TABLE WOULD BE USEFUL FOR THIS QUERY SO YOU WILL NOT LOOSE YOUR ORIGINAL DATA 








 









